### ISSUE TITLE
Can't increment upwards when output voltage too low

### ISSUE THREAD

**Issue by austinbes** [TheUbuntuGuy/psucontrol#7]
I've observed that voltage incrementing doesn't work well below about 12.7 V. The PSU will decrement the voltage, and sometimes increment one or two steps, but no further.

It's unclear whether this is a quirk of my system, my PSU, or of the program itself -- I'll do some testing and see.

**Comment by TheUbuntuGuy** [comment]
All I know from using these at work is that the serial interface is horribly unreliable. Ultimately we bought other supplies because of the weirdness. I would not be surprised if the supplies are doing something that's causing this.

**Comment by austinbes** [comment]
That could definitely be it -- I'm just surprised it's at a specific boundary. The other weird thing is that it still allows manual setting of the voltage -- so the supply hasn't locked up persay, it's specifically the "increment upwards" function. I wonder if there's not some problem with floating-point rounding combined with the float-to-int conversion happening. I plan to spend some time today digging into it.

We recently purchased a few of these for work, specifically to facilitate test automation. What PSUs did you ultimately end up with?

**Comment by TheUbuntuGuy** [comment]
We settled on supplies from http://www.magna-power.com/.
They have a great API and come in variants over 1kV, which we needed for one of our automated test systems. It was easier to standardise things that work rather than messing around with flaky cheap hardware. We still have the BKs, but they are now in less mission critical applications.

**Comment by austinbes** [comment]
Well thanks for the recommendation! And thanks for this little utility -- it's been helpful getting me up and running quickly.
